name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --linelength=120 --filter=-legal/copyright --exclude=tests/src/catch3/catch_amalgamated.cpp --exclude=tests/include/catch3/catch_amalgamated.hpp --recursive .
